"""
Revision ID: 539a0c191ecf
Revises: 
Create Date: 2025-12-02 06:18:56.257894
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '539a0c191ecf'
down_revision = None
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pt_platforms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('api_key', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pt_platforms_project_id'), 'pt_platforms', ['project_id'], unique=False)
    op.create_table('pt_email_inbox',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('platform_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.String(length=255), nullable=False),
    sa.Column('imap_uid', sa.String(length=255), nullable=False),
    sa.Column('from_address', sa.String(length=255), nullable=False),
    sa.Column('from_name', sa.String(length=255), nullable=True),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('ai_reply', sa.Text(), nullable=True),
    sa.Column('raw_headers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['platform_id'], ['pt_platforms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform_id', 'message_id', name='uq_email_inbox_platform_message')
    )
    op.create_index('ix_email_inbox_platform_status', 'pt_email_inbox', ['platform_id', 'status'], unique=False)
    op.create_index('ix_email_inbox_status_fetched', 'pt_email_inbox', ['status', 'fetched_at'], unique=False)
    op.create_index(op.f('ix_pt_email_inbox_platform_id'), 'pt_email_inbox', ['platform_id'], unique=False)
    op.create_index(op.f('ix_pt_email_inbox_project_id'), 'pt_email_inbox', ['project_id'], unique=False)
    op.create_table('pt_wecom_inbox',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('platform_id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.String(length=255), nullable=False),
    sa.Column('from_user', sa.String(length=255), nullable=False),
    sa.Column('open_kfid', sa.String(length=128), nullable=True),
    sa.Column('msg_type', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('is_from_colleague', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('ai_reply', sa.Text(), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['platform_id'], ['pt_platforms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform_id', 'message_id', name='uq_wecom_inbox_platform_message')
    )
    op.create_index(op.f('ix_pt_wecom_inbox_is_from_colleague'), 'pt_wecom_inbox', ['is_from_colleague'], unique=False)
    op.create_index(op.f('ix_pt_wecom_inbox_open_kfid'), 'pt_wecom_inbox', ['open_kfid'], unique=False)
    op.create_index(op.f('ix_pt_wecom_inbox_platform_id'), 'pt_wecom_inbox', ['platform_id'], unique=False)
    op.create_index('ix_wecom_inbox_platform_status', 'pt_wecom_inbox', ['platform_id', 'status'], unique=False)
    op.create_index('ix_wecom_inbox_status_fetched', 'pt_wecom_inbox', ['status', 'fetched_at'], unique=False)
    op.create_table('pt_wukongim_inbox',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('platform_id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.String(length=255), nullable=False),
    sa.Column('client_msg_no', sa.String(length=255), nullable=True),
    sa.Column('from_uid', sa.String(length=255), nullable=False),
    sa.Column('channel_id', sa.String(length=255), nullable=False),
    sa.Column('channel_type', sa.Integer(), nullable=False),
    sa.Column('message_seq', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.Integer(), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('platform_open_id', sa.String(length=255), nullable=True),
    sa.Column('raw_body', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_reply', sa.Text(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('retry_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['platform_id'], ['pt_platforms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform_id', 'message_id', name='uq_wukongim_inbox_platform_message')
    )
    op.create_index(op.f('ix_pt_wukongim_inbox_platform_id'), 'pt_wukongim_inbox', ['platform_id'], unique=False)
    op.create_index(op.f('ix_pt_wukongim_inbox_platform_open_id'), 'pt_wukongim_inbox', ['platform_open_id'], unique=False)
    op.create_index('ix_wukongim_inbox_platform_client_msg_no', 'pt_wukongim_inbox', ['platform_id', 'client_msg_no'], unique=False)
    op.create_index('ix_wukongim_inbox_platform_status_fetched', 'pt_wukongim_inbox', ['platform_id', 'status', 'fetched_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_wukongim_inbox_platform_status_fetched', table_name='pt_wukongim_inbox')
    op.drop_index('ix_wukongim_inbox_platform_client_msg_no', table_name='pt_wukongim_inbox')
    op.drop_index(op.f('ix_pt_wukongim_inbox_platform_open_id'), table_name='pt_wukongim_inbox')
    op.drop_index(op.f('ix_pt_wukongim_inbox_platform_id'), table_name='pt_wukongim_inbox')
    op.drop_table('pt_wukongim_inbox')
    op.drop_index('ix_wecom_inbox_status_fetched', table_name='pt_wecom_inbox')
    op.drop_index('ix_wecom_inbox_platform_status', table_name='pt_wecom_inbox')
    op.drop_index(op.f('ix_pt_wecom_inbox_platform_id'), table_name='pt_wecom_inbox')
    op.drop_index(op.f('ix_pt_wecom_inbox_open_kfid'), table_name='pt_wecom_inbox')
    op.drop_index(op.f('ix_pt_wecom_inbox_is_from_colleague'), table_name='pt_wecom_inbox')
    op.drop_table('pt_wecom_inbox')
    op.drop_index(op.f('ix_pt_email_inbox_project_id'), table_name='pt_email_inbox')
    op.drop_index(op.f('ix_pt_email_inbox_platform_id'), table_name='pt_email_inbox')
    op.drop_index('ix_email_inbox_status_fetched', table_name='pt_email_inbox')
    op.drop_index('ix_email_inbox_platform_status', table_name='pt_email_inbox')
    op.drop_table('pt_email_inbox')
    op.drop_index(op.f('ix_pt_platforms_project_id'), table_name='pt_platforms')
    op.drop_table('pt_platforms')
    # ### end Alembic commands ###