"""Pydantic models for request/response validation."""

from app.schemas.ai_config import (
    AIConfigResponse,
    AIConfigUpdateRequest,
)
from app.schemas.email_schema import (
    EmailConnectionTestRequest,
    EmailConnectionTestResponse,
)

from app.schemas.base import (
    BaseSchema,
    BulkOperationResponse,
    ErrorDetail,
    ErrorResponse,
    HealthCheckResponse,
    PaginatedResponse,
    PaginationMetadata,
    PaginationParams,
    SearchParams,
    SoftDeleteMixin,
    SuccessResponse,
    TimestampMixin,
)
from app.schemas.platform_schema import (
    PlatformAPIKeyResponse,
    PlatformCreate,
    PlatformInDB,
    PlatformListItemResponse,
    PlatformListParams,
    PlatformListResponse,
    PlatformResponse,
    PlatformTypeDefinitionResponse,
    PlatformUpdate,
)
from app.schemas.project import (
    ProjectCreate,
    ProjectInDB,
    ProjectListResponse,
    ProjectResponse,
    ProjectUpdate,
)
from app.schemas.quick_reply import (
    QuickReplyCreate,
    QuickReplyListParams,
    QuickReplyListResponse,
    QuickReplyResponse,
    QuickReplyUpdate,
)
from app.schemas.rag import (
    BatchFileUploadResponse,
    BatchUploadSummary,
    CollectionCreateRequest,
    CollectionDetailResponse,
    CollectionListResponse,
    CollectionResponse,
    CollectionSearchRequest,
    CollectionStats,
    CollectionUpdateRequest,
    FileListResponse,
    FileResponse,
    FileUploadError,
    FileUploadResponse,
    SearchResponse,
    SearchResult,
)
from app.schemas.staff import (
    StaffCreate,
    StaffInDB,
    StaffListParams,
    StaffListResponse,
    StaffLogin,
    StaffLoginResponse,
    StaffResponse,
    StaffUpdate,
)
from app.schemas.setup import (
    ConfigureLLMRequest,
    ConfigureLLMResponse,
    CreateAdminRequest,
    CreateAdminResponse,
    BatchCreateStaffRequest,
    BatchCreateStaffResponse,
    StaffCreatedItem,
    SkipLLMConfigResponse,
    SetupCheckResult,
    SetupStatusResponse,
    VerifySetupResponse,
)
from app.schemas.tag import (
    TagCreate,
    TagInDB,
    TagListParams,
    TagListResponse,
    TagResponse,
    TagUpdate,
    VisitorTagCreate,
    VisitorTagResponse,
)
from app.schemas.visitor_assignment_rule import (
    VisitorAssignmentRuleCreate,
    VisitorAssignmentRuleUpdate,
    VisitorAssignmentRuleResponse,
)
from app.schemas.visitor_assignment_history import (
    VisitorAssignmentHistoryCreate,
    VisitorAssignmentHistoryResponse,
    VisitorAssignmentHistoryDetailResponse,
    VisitorAssignmentHistoryListParams,
    VisitorAssignmentHistoryListResponse,
)
from app.schemas.visitor_session import (
    SessionStatus,
    VisitorSessionCreate,
    VisitorSessionUpdate,
    VisitorSessionResponse,
    VisitorSessionDetailResponse,
    VisitorSessionListParams,
)
from app.schemas.visitor_waiting_queue import (
    WaitingStatusEnum,
    QueueSourceEnum,
    QueueUrgencyEnum,
    WaitingQueueResponse,
    WaitingQueueDetailResponse,
    WaitingQueueListResponse,
    WaitingQueueListParams,
    AcceptVisitorRequest,
    AcceptVisitorResponse,
)
from app.schemas.visitor import (
    VisitorCreate,
    VisitorAttributesUpdate,
    VisitorActivityResponse,
    VisitorInDB,
    VisitorListResponse,
    VisitorResponse,
    VisitorBasicResponse,
    VisitorSystemInfoRequest,
    VisitorSystemInfoResponse,
    VisitorUpdate,
    VisitorAvatarUploadResponse,
    VisitorRegisterRequest,
    VisitorRegisterResponse,
    VisitorMessageSyncRequest,
)
from app.schemas.visitor_activity import (
    VisitorActivityContext,
    VisitorActivityCreateRequest,
    VisitorActivityCreateResponse,
    VisitorActivityType,
)
from app.schemas.wukongim import (
    WuKongIMChannelMessageSyncRequest,
    WuKongIMChannelMessageSyncResponse,
    WuKongIMConversation,
    WuKongIMConversationSyncRequest,
    WuKongIMConversationSyncResponse,
    WuKongIMDeleteConversationRequest,
    WuKongIMDeviceKickRequest,
    WuKongIMIntegrationStatus,
    WuKongIMMessage,
    WuKongIMMessageHeader,
    WuKongIMOnlineStatusRequest,
    WuKongIMOnlineStatusResponse,
    WuKongIMSetUnreadRequest,
    WuKongIMSystemAccountsRequest,
    WuKongIMUserRegistration,
)
from app.schemas.search import MessageSearchResult, SearchPagination, SearchScope, UnifiedSearchResponse
from app.schemas.chat import (
    ChatFileUploadResponse,
    StaffSendPlatformMessageRequest,
    OpenAIChatMessage,
    OpenAIChatCompletionRequest,
    OpenAIChatCompletionChoice,
    OpenAIChatCompletionUsage,
    OpenAIChatCompletionResponse,
    OpenAIChatCompletionDelta,
    OpenAIChatCompletionChunkChoice,
    OpenAIChatCompletionChunk,
)

__all__ = [
    # Base schemas
    "BaseSchema",
    "TimestampMixin",
    "SoftDeleteMixin",
    "PaginationParams",
    "PaginationMetadata",
    "PaginatedResponse",
    "ErrorDetail",
    "ErrorResponse",
    "SuccessResponse",
    "HealthCheckResponse",
    "BulkOperationResponse",
    "SearchParams",
    # AI config schemas
    "AIConfigResponse",
    "AIConfigUpdateRequest",
    # Project schemas
    "ProjectCreate",
    "ProjectUpdate",
    "ProjectInDB",
    "ProjectResponse",
    "ProjectListResponse",
    # Quick reply schemas
    "QuickReplyCreate",
    "QuickReplyUpdate",
    "QuickReplyResponse",
    "QuickReplyListParams",
    "QuickReplyListResponse",
    # Platform schemas
    "PlatformCreate",
    "PlatformUpdate",
    "PlatformAPIKeyResponse",
    "PlatformInDB",
    "PlatformListItemResponse",
    "PlatformResponse",
    "PlatformListParams",
    "PlatformListResponse",
    "PlatformTypeDefinitionResponse",
    # Staff schemas
    "StaffCreate",
    "StaffUpdate",
    "StaffInDB",
    "StaffResponse",
    "StaffListParams",
    "StaffListResponse",
    "StaffLogin",
    "StaffLoginResponse",
    # Setup schemas
    "SetupStatusResponse",
    "CreateAdminRequest",
    "CreateAdminResponse",
    "BatchCreateStaffRequest",
    "BatchCreateStaffResponse",
    "StaffCreatedItem",
    "ConfigureLLMRequest",
    "ConfigureLLMResponse",
    "SkipLLMConfigResponse",
    "SetupCheckResult",
    "VerifySetupResponse",
    # Visitor schemas
    "VisitorCreate",
    "VisitorAttributesUpdate",
    "VisitorActivityResponse",
    "VisitorActivityCreateRequest",
    "VisitorActivityCreateResponse",
    "VisitorActivityType",
    "VisitorActivityContext",
    "VisitorSystemInfoRequest",
    "VisitorSystemInfoResponse",
    "VisitorUpdate",
    "VisitorInDB",
    "VisitorResponse",
    "VisitorBasicResponse",
    "VisitorListResponse",
    "VisitorAvatarUploadResponse",
    # Tag schemas
    "TagCreate",
    "TagUpdate",
    "TagInDB",
    "TagResponse",
    "TagListParams",
    "TagListResponse",
    "VisitorTagCreate",
    "VisitorTagResponse",
    # Visitor Assignment Rule schemas
    "VisitorAssignmentRuleCreate",
    "VisitorAssignmentRuleUpdate",
    "VisitorAssignmentRuleResponse",
    # Visitor Assignment History schemas
    "VisitorAssignmentHistoryCreate",
    "VisitorAssignmentHistoryResponse",
    "VisitorAssignmentHistoryDetailResponse",
    "VisitorAssignmentHistoryListParams",
    "VisitorAssignmentHistoryListResponse",
    # Visitor Session schemas
    "SessionStatus",
    "VisitorSessionCreate",
    "VisitorSessionUpdate",
    "VisitorSessionResponse",
    "VisitorSessionDetailResponse",
    "VisitorSessionListParams",
    # Visitor Waiting Queue schemas
    "WaitingStatusEnum",
    "QueueSourceEnum",
    "QueueUrgencyEnum",
    "WaitingQueueResponse",
    "WaitingQueueDetailResponse",
    "WaitingQueueListResponse",
    "WaitingQueueListParams",
    "AcceptVisitorRequest",
    "AcceptVisitorResponse",
    # Email schemas
    "EmailConnectionTestRequest",
    "EmailConnectionTestResponse",
    # RAG schemas
    "CollectionCreateRequest",
    "CollectionResponse",
    "CollectionDetailResponse",
    "CollectionListResponse",
    "CollectionSearchRequest",
    "CollectionStats",
    "CollectionUpdateRequest",
    "SearchResult",
    "SearchResponse",
    "FileResponse",
    "FileListResponse",
    "FileUploadResponse",
    "FileUploadError",
    "BatchUploadSummary",
    "BatchFileUploadResponse",
    # Chat schemas
    "ChatFileUploadResponse",
    "StaffSendPlatformMessageRequest",
    "OpenAIChatMessage",
    "OpenAIChatCompletionRequest",
    "OpenAIChatCompletionChoice",
    "OpenAIChatCompletionUsage",
    "OpenAIChatCompletionResponse",
    "OpenAIChatCompletionDelta",
    "OpenAIChatCompletionChunkChoice",
    "OpenAIChatCompletionChunk",
    # Search schemas
    "SearchScope",
    "MessageSearchResult",
    "SearchPagination",
    "UnifiedSearchResponse",
    # WuKongIM schemas
    "WuKongIMChannelMessageSyncRequest",
    "WuKongIMChannelMessageSyncResponse",
    "WuKongIMConversation",
    "WuKongIMConversationSyncRequest",
    "WuKongIMConversationSyncResponse",
    "WuKongIMDeleteConversationRequest",
    "WuKongIMDeviceKickRequest",
    "WuKongIMIntegrationStatus",
    "WuKongIMMessage",
    "WuKongIMMessageHeader",
    "WuKongIMOnlineStatusRequest",
    "WuKongIMOnlineStatusResponse",
    "WuKongIMSetUnreadRequest",
    "WuKongIMSystemAccountsRequest",
    "WuKongIMUserRegistration",
]
