"""init

Revision ID: 6595c48378f1
Revises: 
Create Date: 2025-12-02 06:16:01.593436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6595c48378f1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_ai_models',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False, comment='Provider key (openai, anthropic, dashscope, azure_openai)'),
    sa.Column('model_id', sa.String(length=100), nullable=False, comment='Model identifier (e.g., gpt-4, claude-3-opus, qwen-max)'),
    sa.Column('model_name', sa.String(length=100), nullable=False, comment='Display name for the model'),
    sa.Column('model_type', sa.String(length=20), nullable=False, comment='Model type: chat or embedding'),
    sa.Column('description', sa.String(length=255), nullable=True, comment='Optional description of the model'),
    sa.Column('capabilities', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Model capabilities JSON, e.g., {vision: true, function_calling: true}'),
    sa.Column('context_window', sa.Integer(), nullable=True, comment='Context window size (tokens)'),
    sa.Column('max_tokens', sa.Integer(), nullable=True, comment='Maximum output tokens'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether this model is enabled'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Creation timestamp'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Last update timestamp'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Soft deletion timestamp'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'model_id', name='uq_ai_models_provider_model_id')
    )
    op.create_index(op.f('ix_api_ai_models_model_type'), 'api_ai_models', ['model_type'], unique=False)
    op.create_table('api_platform_types',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False, comment='Stable identifier (e.g., wechat, website, email)'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Human-readable platform name'),
    sa.Column('name_en', sa.String(length=100), nullable=True, comment="English name of the platform type (e.g., 'WeCom', 'Website')"),
    sa.Column('is_supported', sa.Boolean(), nullable=False, comment='Whether this platform type is currently supported'),
    sa.Column('icon', sa.Text(), nullable=True, comment='SVG icon markup for display'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Creation timestamp'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Last update timestamp'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type')
    )
    op.create_table('api_projects',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Project name'),
    sa.Column('api_key', sa.String(length=255), nullable=False, comment='API key for authentication'),
    sa.Column('default_team_id', sa.String(length=64), nullable=True, comment='Default AI team ID from AI service'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Creation timestamp'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Last update timestamp'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Soft deletion timestamp'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_key')
    )
    op.create_table('api_system_setup',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('is_installed', sa.Boolean(), nullable=False),
    sa.Column('admin_created', sa.Boolean(), nullable=False),
    sa.Column('llm_configured', sa.Boolean(), nullable=False),
    sa.Column('skip_llm_config', sa.Boolean(), nullable=False),
    sa.Column('setup_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('setup_version', sa.String(length=50), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('api_ai_providers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False, comment='Associated project ID for multi-tenant isolation'),
    sa.Column('provider', sa.String(length=50), nullable=False, comment='Provider key (e.g., openai, anthropic, dashscope, azure_openai)'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Display name / alias shown in UI'),
    sa.Column('api_key', sa.String(length=255), nullable=False, comment='API key/credential used to call the provider'),
    sa.Column('api_base_url', sa.String(length=255), nullable=True, comment='Base URL for the provider API (if applicable)'),
    sa.Column('available_models', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='List of available model identifiers for this provider'),
    sa.Column('default_model', sa.String(length=100), nullable=True, comment='Default model identifier to use'),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Additional provider-specific configuration'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether this provider configuration is enabled'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Creation timestamp'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Last update timestamp'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Soft deletion timestamp'),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True, comment='Last synced to AI service timestamp'),
    sa.Column('sync_status', sa.String(length=20), nullable=True, comment='Sync status: pending|synced|failed'),
    sa.Column('sync_error', sa.Text(), nullable=True, comment='Last sync error message'),
    sa.ForeignKeyConstraint(['project_id'], ['api_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('api_channel_members',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False, comment='Associated project ID for multi-tenant isolation'),
    sa.Column('channel_id', sa.String(length=255), nullable=False, comment='WuKongIM channel ID (Base62-encoded)'),
    sa.Column('channel_type', sa.Integer(), nullable=False, comment='WuKongIM channel type (e.g., 251 for customer service)'),
    sa.Column('member_id', sa.Uuid(), nullable=False, comment='Member UUID (either Visitor.id or Staff.id)'),
    sa.Column('member_type', sa.String(length=20), nullable=False, comment="Member type: 'visitor' or 'staff'"),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Creation timestamp'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Last update timestamp'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Soft deletion timestamp'),
    sa.CheckConstraint("member_type IN ('visitor', 'staff')", name='chk_api_channel_members_type'),
    sa.ForeignKeyConstraint(['project_id'], ['api_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_id', 'member_id', 'deleted_at', name='uk_api_channel_members_channel_member_deleted')
    )
    op.create_index('ix_api_channel_members_channel_member', 'api_channel_members', ['channel_id', 'member_id'], unique=False)
    op.create_index('ix_api_channel_members_member_id', 'api_channel_members', ['member_id'], unique=False)
    op.create_index('ix_api_channel_members_project_id', 'api_channel_members', ['project_id'], unique=False)
    op.create_table('api_chat_files',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False, comment='Associated project ID'),
    sa.Column('channel_id', sa.String(length=255), nullable=False, comment='Channel identifier'),
    sa.Column('channel_type', sa.Integer(), nullable=False, comment='Channel type code'),
    sa.Column('file_name', sa.String(length=255), nullable=False, comment='Original filename'),
    sa.Column('file_path', sa.String(length=1024), nullable=False, comment='Relative path from base upload directory'),
    sa.Column('file_size', sa.Integer(), nullable=False, comment='File size in bytes'),
    sa.Column('file_type', sa.String(length=255), nullable=False, comment='MIME type'),
    sa.Column('uploaded_by_staff_id', sa.Uuid(), nullable=True, comment='Staff ID if uploaded by staff'),
    sa.Column('uploaded_by_platform_id', sa.Uuid(), nullable=True, comment='Platform ID if uploaded via platform API key'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Creation time'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Update time'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Soft deletion time'),
    sa.ForeignKeyConstraint(['project_id'], ['api_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('api_platforms',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False, comment='Associated project ID for multi-tenant isolation'),
    sa.Column('name', sa.String(length=100), nullable=True, comment='Platform name (e.g., WeChat, WhatsApp)'),
    sa.Column('type', sa.String(length=20), nullable=False, comment='Platform type from predefined enum'),
    sa.Column('api_key', sa.String(length=255), nullable=True, comment='Platform-specific API key for integrations'),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Platform-specific configuration'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether platform is active'),
    sa.Column('ai_disabled', sa.Boolean(), nullable=True, comment='Whether AI responses are disabled for this platform'),
    sa.Column('logo_path', sa.String(length=512), nullable=True, comment='Relative path to logo file under PLATFORM_LOGO_UPLOAD_DIR'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Creation timestamp'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Last update timestamp'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Soft deletion timestamp'),
    sa.Column('sync_status', sa.String(length=20), nullable=False, comment='Synchronization status with Platform Service (pending|synced|failed)'),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True, comment='Timestamp of last successful sync'),
    sa.Column('sync_error', sa.Text(), nullable=True, comment='Last synchronization error message'),
    sa.Column('sync_retry_count', sa.Integer(), nullable=False, comment='Number of sync retry attempts'),
    sa.ForeignKeyConstraint(['project_id'], ['api_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('api_project_onboarding_progress',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False, comment='Associated project ID (unique)'),
    sa.Column('step_1_completed', sa.Boolean(), nullable=False, comment='Whether AI provider setup is completed'),
    sa.Column('step_2_completed', sa.Boolean(), nullable=False, comment='Whether default models are configured'),
    sa.Column('step_3_completed', sa.Boolean(), nullable=False, comment='Whether RAG collection is created'),
    sa.Column('step_4_completed', sa.Boolean(), nullable=False, comment='Whether agent with knowledge base is created'),
    sa.Column('step_5_completed', sa.Boolean(), nullable=False, comment='Whether first chat is started'),
    sa.Column('is_completed', sa.Boolean(), nullable=False, comment='Whether all onboarding steps are completed or skipped'),
    sa.Column('completed_at', sa.DateTime(), nullable=True, comment='Timestamp when onboarding was completed or skipped'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['api_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', name='uq_project_onboarding_project_id')
    )
    op.create_table('api_staff',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False, comment='Associated project ID for multi-tenant isolation'),
    sa.Column('username', sa.String(length=50), nullable=False, comment='Staff username for login'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='Hashed password for authentication (bcrypt, argon2, etc.)'),
    sa.Column('nickname', sa.String(length=100), nullable=True, comment='Staff display name'),
    sa.Column('avatar_url', sa.String(length=255), nullable=True, comment='Staff avatar URL'),
    sa.Column('role', sa.String(length=20), nullable=False, comment='Staff role: user or agent'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='Staff status: online, offline, busy'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Creation timestamp'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Last update timestamp'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Soft deletion timestamp'),
    sa.CheckConstraint("role IN ('user', 'agent')", name='chk_api_staff_role'),
    sa.CheckConstraint("status IN ('online', 'offline', 'busy')", name='chk_api_staff_status'),
    sa.ForeignKeyConstraint(['project_id'], ['api_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('api_tags',
    sa.Column('id', sa.String(length=255), nullable=False, comment="Base64 encoded ID: base64_encode(name + '@' + category)"),
    sa.Column('project_id', sa.Uuid(), nullable=False, comment='Associated project ID for multi-tenant isolation'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='Tag name'),
    sa.Column('category', sa.String(length=20), nullable=False, comment='Tag category: visitor (for customer categorization) or knowledge (for content categorization)'),
    sa.Column('weight', sa.Integer(), nullable=False, comment='Tag importance/priority weight (0-10, higher values indicate higher priority)'),
    sa.Column('color', sa.String(length=20), nullable=True, comment='Tag color'),
    sa.Column('description', sa.String(length=255), nullable=True, comment='Tag description'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Creation timestamp'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Last update timestamp'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Soft deletion timestamp'),
    sa.CheckConstraint("category IN ('visitor', 'knowledge')", name='chk_api_tags_category'),
    sa.CheckConstraint('weight >= 0 AND weight <= 10', name='chk_api_tags_weight'),
    sa.ForeignKeyConstraint(['project_id'], ['api_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'name', name='uk_api_tags_project_name')
    )
    op.create_table('api_visitors',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False, comment='Associated project ID for multi-tenant isolation'),
    sa.Column('platform_id', sa.Uuid(), nullable=False, comment='Associated platform ID'),
    sa.Column('platform_open_id', sa.String(length=255), nullable=False, comment='Visitor unique identifier on this platform'),
    sa.Column('name', sa.String(length=100), nullable=True, comment='Visitor real name'),
    sa.Column('nickname', sa.String(length=100), nullable=True, comment='Visitor nickname on this platform'),
    sa.Column('avatar_url', sa.String(length=255), nullable=True, comment='Visitor avatar URL on this platform'),
    sa.Column('phone_number', sa.String(length=30), nullable=True, comment='Visitor phone number on this platform'),
    sa.Column('email', sa.String(length=255), nullable=True, comment='Visitor email on this platform'),
    sa.Column('company', sa.String(length=255), nullable=True, comment='Visitor company or organization'),
    sa.Column('job_title', sa.String(length=255), nullable=True, comment='Visitor job title or position'),
    sa.Column('source', sa.String(length=255), nullable=True, comment='Acquisition source describing how the visitor found us'),
    sa.Column('note', sa.Text(), nullable=True, comment='Additional notes about the visitor'),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Arbitrary custom attributes set by staff'),
    sa.Column('first_visit_time', sa.DateTime(), nullable=False, comment='When the visitor first accessed the system'),
    sa.Column('last_visit_time', sa.DateTime(), nullable=False, comment='Visitor most recent activity/visit time'),
    sa.Column('last_offline_time', sa.DateTime(), nullable=True, comment='Most recent time visitor went offline (NULL when never offline or currently online)'),
    sa.Column('is_online', sa.Boolean(), nullable=False, comment='Whether the visitor is currently online/active'),
    sa.Column('ai_disabled', sa.Boolean(), nullable=True, comment='Whether AI responses are disabled for this visitor'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Creation timestamp'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Last update timestamp'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Soft deletion timestamp'),
    sa.ForeignKeyConstraint(['project_id'], ['api_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('api_manual_service_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False, comment='Associated project ID for multi-tenant isolation'),
    sa.Column('visitor_id', sa.Uuid(), nullable=True, comment='Visitor that triggered the manual service request'),
    sa.Column('reason', sa.Text(), nullable=False, comment='Reason for requesting manual assistance'),
    sa.Column('urgency', sa.String(length=10), nullable=False, comment='Urgency level: low | normal | high | urgent'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='Status of the manual service request: pending, notified, in_progress, resolved, rejected'),
    sa.Column('channel', sa.String(length=50), nullable=True, comment='Preferred manual service channel (phone/wechat/email/ticket/etc.)'),
    sa.Column('notification_type', sa.String(length=50), nullable=True, comment='Notification modality used to alert staff (e.g., sms, email, slack)'),
    sa.Column('channel_id', sa.String(length=255), nullable=True, comment='Associated communication channel identifier'),
    sa.Column('channel_type', sa.Integer(), nullable=True, comment='Associated communication channel type code'),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Additional contextual metadata for the request'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Creation timestamp'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Last update timestamp'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Soft deletion timestamp'),
    sa.CheckConstraint("status IN ('pending', 'notified', 'in_progress', 'resolved', 'rejected')", name='chk_manual_service_requests_status'),
    sa.CheckConstraint("urgency IN ('low', 'normal', 'high', 'urgent')", name='chk_manual_service_requests_urgency'),
    sa.ForeignKeyConstraint(['project_id'], ['api_projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['visitor_id'], ['api_visitors.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('api_project_ai_configs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False, comment='Associated project ID (unique)'),
    sa.Column('default_chat_provider_id', sa.Uuid(), nullable=True, comment='AIProvider ID for default chat model'),
    sa.Column('default_chat_model', sa.String(length=100), nullable=True, comment='Default chat model identifier'),
    sa.Column('default_embedding_provider_id', sa.Uuid(), nullable=True, comment='AIProvider ID for default embedding model'),
    sa.Column('default_embedding_model', sa.String(length=100), nullable=True, comment='Default embedding model identifier'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('sync_status', sa.String(length=20), nullable=True),
    sa.Column('sync_error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['default_chat_provider_id'], ['api_ai_providers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['default_embedding_provider_id'], ['api_ai_providers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['api_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', name='uq_project_ai_config_project_id')
    )
    op.create_table('api_visitor_activities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False, comment='Associated project ID for multi-tenant isolation'),
    sa.Column('visitor_id', sa.Uuid(), nullable=False, comment='Associated visitor ID'),
    sa.Column('activity_type', sa.String(length=50), nullable=False, comment='Categorised type of activity'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='Short title or headline for the activity'),
    sa.Column('description', sa.Text(), nullable=True, comment='Detailed description of the activity'),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Arbitrary structured context for the activity'),
    sa.Column('duration_seconds', sa.Integer(), nullable=True, comment='Duration associated with the activity, in seconds'),
    sa.Column('occurred_at', sa.DateTime(), nullable=False, comment='When the activity occurred'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Record update timestamp'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Soft deletion timestamp'),
    sa.ForeignKeyConstraint(['project_id'], ['api_projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['visitor_id'], ['api_visitors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('api_visitor_ai_insights',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False, comment='Associated project ID for multi-tenant isolation'),
    sa.Column('visitor_id', sa.Uuid(), nullable=False, comment='Associated visitor ID'),
    sa.Column('satisfaction_score', sa.Integer(), nullable=True, comment='Latest satisfaction score on a 0-5 scale (0=unknown)'),
    sa.Column('emotion_score', sa.Integer(), nullable=True, comment='Latest emotion score on a 0-5 scale (0=unknown)'),
    sa.Column('intent', sa.String(length=50), nullable=True, comment='Visitor intent classification (e.g., purchase, inquiry, complaint, support)'),
    sa.Column('insight_summary', sa.String(length=500), nullable=True, comment='Brief natural language summary of the insight'),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Additional metadata for the AI insight'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Creation timestamp'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Last update timestamp'),
    sa.ForeignKeyConstraint(['project_id'], ['api_projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['visitor_id'], ['api_visitors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('visitor_id', name='uk_api_visitor_ai_insight_visitor')
    )
    op.create_table('api_visitor_ai_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False, comment='Associated project ID for multi-tenant isolation'),
    sa.Column('visitor_id', sa.Uuid(), nullable=False, comment='Associated visitor ID'),
    sa.Column('persona_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='List of AI generated persona tags'),
    sa.Column('summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Structured summary data for AI persona'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Creation timestamp'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Last update timestamp'),
    sa.ForeignKeyConstraint(['project_id'], ['api_projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['visitor_id'], ['api_visitors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('visitor_id', name='uk_api_visitor_ai_profile_visitor')
    )
    op.create_table('api_visitor_assignments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False, comment='Associated project ID for multi-tenant isolation'),
    sa.Column('visitor_id', sa.Uuid(), nullable=False, comment='Assigned visitor'),
    sa.Column('assigned_staff_id', sa.Uuid(), nullable=True, comment='Currently assigned staff member'),
    sa.Column('previous_staff_id', sa.Uuid(), nullable=True, comment='Previously assigned staff member'),
    sa.Column('assigned_by_staff_id', sa.Uuid(), nullable=True, comment='Staff member who made the assignment'),
    sa.Column('assignment_type', sa.String(length=20), nullable=False, comment='Type of assignment: assign, reassign, unassign, auto_assign'),
    sa.Column('timestamp', sa.DateTime(), nullable=False, comment='When assignment was made'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Assignment notes'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Creation timestamp'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Last update timestamp'),
    sa.CheckConstraint("assignment_type IN ('assign', 'reassign', 'unassign', 'auto_assign')", name='chk_api_visitor_assignments_type'),
    sa.ForeignKeyConstraint(['assigned_by_staff_id'], ['api_staff.id'], ),
    sa.ForeignKeyConstraint(['assigned_staff_id'], ['api_staff.id'], ),
    sa.ForeignKeyConstraint(['previous_staff_id'], ['api_staff.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['api_projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['visitor_id'], ['api_visitors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('api_visitor_customer_updates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False, comment='Associated project ID for multi-tenant isolation'),
    sa.Column('visitor_id', sa.Uuid(), nullable=False, comment='Visitor whose information was updated'),
    sa.Column('source', sa.String(length=100), nullable=False, comment='Source identifier for the update event'),
    sa.Column('channel_id', sa.String(length=255), nullable=True, comment='Channel identifier associated with the update event'),
    sa.Column('channel_type', sa.Integer(), nullable=True, comment='Channel type associated with the update event'),
    sa.Column('customer_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Snapshot of customer data provided in the event'),
    sa.Column('changes_applied', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Dictionary of applied changes {field: {"old": val, "new": val}}'),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Additional metadata accompanying the update event'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Creation timestamp'),
    sa.ForeignKeyConstraint(['project_id'], ['api_projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['visitor_id'], ['api_visitors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('api_visitor_system_info',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False, comment='Associated project ID for multi-tenant isolation'),
    sa.Column('visitor_id', sa.Uuid(), nullable=False, comment='Associated visitor ID'),
    sa.Column('platform', sa.String(length=100), nullable=True, comment='Acquisition or support platform name'),
    sa.Column('source_detail', sa.String(length=255), nullable=True, comment='Additional context for the visitor source'),
    sa.Column('browser', sa.String(length=100), nullable=True, comment='Latest known browser'),
    sa.Column('operating_system', sa.String(length=100), nullable=True, comment='Latest known operating system'),
    sa.Column('first_seen_at', sa.DateTime(), nullable=True, comment='Timestamp of the first tracked session'),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True, comment='Timestamp of the last tracked session'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Creation timestamp'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Last update timestamp'),
    sa.ForeignKeyConstraint(['project_id'], ['api_projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['visitor_id'], ['api_visitors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('visitor_id', name='uk_api_visitor_system_info_visitor')
    )
    op.create_table('api_visitor_tags',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False, comment='Associated project ID for multi-tenant isolation'),
    sa.Column('visitor_id', sa.Uuid(), nullable=False, comment='Associated visitor ID'),
    sa.Column('tag_id', sa.String(length=255), nullable=False, comment='Associated tag ID (Base64 encoded)'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Creation timestamp'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Last update timestamp'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Soft deletion timestamp'),
    sa.ForeignKeyConstraint(['project_id'], ['api_projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['api_tags.id'], ),
    sa.ForeignKeyConstraint(['visitor_id'], ['api_visitors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('visitor_id', 'tag_id', name='uk_api_visitor_tags_visitor_tag')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('api_visitor_tags')
    op.drop_table('api_visitor_system_info')
    op.drop_table('api_visitor_customer_updates')
    op.drop_table('api_visitor_assignments')
    op.drop_table('api_visitor_ai_profiles')
    op.drop_table('api_visitor_ai_insights')
    op.drop_table('api_visitor_activities')
    op.drop_table('api_project_ai_configs')
    op.drop_table('api_manual_service_requests')
    op.drop_table('api_visitors')
    op.drop_table('api_tags')
    op.drop_table('api_staff')
    op.drop_table('api_project_onboarding_progress')
    op.drop_table('api_platforms')
    op.drop_table('api_chat_files')
    op.drop_index('ix_api_channel_members_project_id', table_name='api_channel_members')
    op.drop_index('ix_api_channel_members_member_id', table_name='api_channel_members')
    op.drop_index('ix_api_channel_members_channel_member', table_name='api_channel_members')
    op.drop_table('api_channel_members')
    op.drop_table('api_ai_providers')
    op.drop_table('api_system_setup')
    op.drop_table('api_projects')
    op.drop_table('api_platform_types')
    op.drop_index(op.f('ix_api_ai_models_model_type'), table_name='api_ai_models')
    op.drop_table('api_ai_models')
    # ### end Alembic commands ###